spring.datasource.url=jdbc:postgresql://localhost:5432/talentobr
spring.datasource.username=talentobr
spring.datasource.password=talentobr

spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=true

spring.thymeleaf.cache=false